export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const CHANGE_TASK = 'CHANGE_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const LOADING_TASKS = 'LOADING_TASKS';
export const TASKS_LOADING_SUCCESS = 'TASKS_LOADING_SUCCESS';
